### ISSUE TITLE
Make init-env container optional

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/helm-charts#1]
Now, we use `init-env` container as way to pass Kubernetes worker node Public IP to Codex.

That works well, but not required all the time. And now we enable it by default is some cases
> `# Enable init Env container - enabled automatically when replica.count > 1 and service.type.nodeport`

We should add a way to disable it.

And to be mentioned - we have at least 2 additional ways to pass node Public IP using environment variables
```yaml
# IP lookup service
NAT_PUBLIC_IP_AUTO: https://ip.codex.storage

# Static
CODEX_NAT: x.x.x.x
```
